- name: Install MariaDB server
  apt:
    name: "{{ db_engine }}"
    state: present

- name: Configure bind-address (optional first pass)
  copy:
    dest: /etc/mysql/conf.d/bind_address.cnf
    content: |
      [mysqld]
      bind-address = {{ mysql_bind_address }}
  notify: Restart MariaDB

- name: Ensure MariaDB is enabled and running
  service:
    name: mariadb
    state: started
    enabled: yes